### ISSUE TITLE
Enrolled name

### ISSUE THREAD

**Issue by brandonfranzke** [Rajesh20dec/EE511#1]
Please reply with the name you have registered in EE511 class. I am having trouble locating you in my roster. Thanks!

**Comment by brandonfranzke** [comment]
@Rajesh20dec

**Comment by Rajesh20dec** [comment]
@brandonfranzke 
My name is Rajesh kumar.

Thanks!!

**Comment by brandonfranzke** [comment]
Thanks.  Have a great summer!
